name: Britive-GitHub Federated Access for Azure via OpenID Connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  federated-azure-access:
    runs-on: ubuntu-latest

    steps:
      - name: Install pybritive
        run: |
          pip install pybritive --quiet

      - name: Checkout Azure access from Britive and login
        run: |
          echo "Checking out Azure login command from Britive..."

          # Disable command echo to hide sensitive output
          set +x
          LOGIN_CMD=$(pybritive checkout -t demo.britive-app.com "Azure/Azure/Azure AD - Directory Reader" -m azlogin -P github-britive | grep '^az login')
          set -x

          # Login to Azure with the command from Britive
          eval "$LOGIN_CMD"

      - name: Confirm Azure access (safe output only)
        run: |
          echo "Confirming Azure login..."
          az account show --query "{subscription:name, userType:user.type}" --output json
