name: Britive-GitHub Federated Access for Azure Keyless via OpenID Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC

permissions:
  id-token: write
  contents: read

jobs:
  federated-azure-access:
    runs-on: ubuntu-latest

    env:
      BRITIVE_TENANT: demo
      BRITIVE_PROFILE_NAME: Britive Azure Tenant/Britive Azure Tenant/Azure AD - Directory Reader
      FED_PROVIDER: github-britive
      AZURE_REGION: eastus

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pybritive and Azure CLI
        run: |
          pip install pybritive --quiet
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Configure Britive and Azure Credential Process
        run: |
          # Create Azure profile using pybritive
          pybritive configure update profile-aliases azure "$BRITIVE_PROFILE_NAME"

          # Run pybritive to get a federated token and configure Azure CLI
          eval "$(pybritive checkout azure -m azurecredentialprocess -P $FED_PROVIDER --shell)"
          
          # Confirm identity for debug
          az account show

      - name: Test Azure Access - List VMs
        run: |
          echo "Listing Azure VMs..."
          az vm list --output table
