name: Britive-GitHub Federated Access for Azure via OpenID Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
permissions:
  id-token: write
  contents: read

jobs:
  federated-azure-access:
    runs-on: ubuntu-latest

    steps:
      - name: Install pybritive
        run: |
          pip install pybritive --quiet

      - name: Checkout Azure access from Britive and login
        run: |
          echo "Checking out Azure login command from Britive..."

          # Turn off command echoing
          set +x

          # Run pybritive and eval the login, suppressing az output
          pybritive checkout -t demo.britive-app.com "Azure/Azure/Azure AD - Directory Reader" -m azlogin -P github-britive | grep '^az login' > login.sh
          chmod +x login.sh
          ./login.sh > /dev/null 2>&1

          # Turn echoing back on
          set -x

      - name: Confirm Azure access (safe output only)
        run: |
          echo "Confirming Azure login..."
          az account show --query "{subscription:name, userType:user.type}" --output json
