name: Britive-GitHub Federated Access for Azure via OpenID Connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  federated-azure-access:
    runs-on: ubuntu-latest

    steps:
      - name: Install pybritive
        run: |
          pip install pybritive --quiet

      - name: Checkout access from Britive and login to Azure
        run: |
          # Use pybritive to output a ready-to-use az login command
          LOGIN_CMD=$(pybritive checkout -t demo.britive-app.com "Azure/Azure/Azure AD - Directory Reader" -m azlogin -P github-britive)

          # Evaluate the login command directly
          eval "$LOGIN_CMD"

      - name: Confirm Azure Access
        run: |
          az account show
