name: Britive-GitHub Federated Access for Azure via OpenID Connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  federated-azure-access:
    runs-on: ubuntu-latest

    env:
      BRITIVE_TENANT: demo
      BRITIVE_PROFILE_NAME: Britive Azure Tenant/Britive Azure Tenant/Directory Reader
      FED_PROVIDER: github-britive

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pybritive
        run: |
          pip install pybritive --quiet

      - name: Authenticate to Azure via Britive
        run: |
          # Set up alias to map to your full Britive profile path
          pybritive configure update profile-aliases azure "$BRITIVE_PROFILE_NAME"

          # Checkout secret from Britive (SP credentials for Azure)
          CREDS=$(pybritive checkout azure -m secret -P "$FED_PROVIDER" --json)

          CLIENT_ID=$(echo "$CREDS" | jq -r '.credentials.username')
          CLIENT_SECRET=$(echo "$CREDS" | jq -r '.credentials.password')
          TENANT_ID=$(echo "$CREDS" | jq -r '.credentials.tenant')

          # Authenticate to Azure using az CLI and Britive-issued credentials
          az login \
            --service-principal \
            --username "$CLIENT_ID" \
            --password "$CLIENT_SECRET" \
            --tenant "$TENANT_ID"

      - name: Test Azure Access
        run: |
          az account show
